# Generated by Django 5.2.1 on 2025-05-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcr_back', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerReport',
            new_name='CustomerData',
        ),
    ]
